/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DropList: typeof import('./src/components/DropList/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListScroll: typeof import('./src/components/scroll/ListScroll.vue')['default']
    Picker: typeof import('./src/components/picker/index.vue')['default']
    Popup: typeof import('./src/components/popup/index.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Tabbar: typeof import('./src/components/tabbar/index.vue')['default']
    VanCard: typeof import('vant/es')['Card']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
